name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["main", "test-ssh-dbg"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:

      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
        with:
          wait-timeout-minutes: 5

      - name: General
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: general.svg
          output_action: gist
          committer_gist: ${{ secrets.COMITTER_GIST }}
          base: header
          config_timezone: BR/Sao_Paulo
          config_order: base.header, isocalendar, languages, notable, discussions, topics

          # Plugin isocalendar
          plugin_isocalendar: yes

          # Plugin languages
          plugin_languages: yes
          #plugin_languages_indepth: yes
          plugin_languages_ignored: makefile, cmake, css, xslt
          #plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_details: bytes-size, percentage
          #(recently-used not working) plugin_languages_sections: most-used, recently-used
          plugin_languages_sections: most-used
          plugin_languages_limit: 10

          # Plugin topics
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons
